// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketConsoleApp;

#nullable disable

namespace SupermarketConsoleApp.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20230220131413_manhs")]
    partial class manhs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupermarketConsoleApp.Ishchilar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Ishchilar");
                });

            modelBuilder.Entity("SupermarketConsoleApp.Mahsulotlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Xaridlarid")
                        .HasColumnType("int");

                    b.Property<int>("narxi")
                        .HasColumnType("int");

                    b.Property<string>("nomi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yaroqlilikMuddati")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Xaridlarid");

                    b.ToTable("Mahsulotlar");
                });

            modelBuilder.Entity("SupermarketConsoleApp.Xaridlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("usum")
                        .HasColumnType("int");

                    b.Property<string>("vaqti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Xaridlar");
                });

            modelBuilder.Entity("SupermarketConsoleApp.Mahsulotlar", b =>
                {
                    b.HasOne("SupermarketConsoleApp.Xaridlar", null)
                        .WithMany("XMahsulotlari")
                        .HasForeignKey("Xaridlarid");
                });

            modelBuilder.Entity("SupermarketConsoleApp.Xaridlar", b =>
                {
                    b.Navigation("XMahsulotlari");
                });
#pragma warning restore 612, 618
        }
    }
}
